### ISSUE TITLE
Fix unecessary rebuild

### ISSUE THREAD

**Issue by kevin-sakemaer** [rushio-consulting/formation_flutter_app#2]
https://github.com/rushio-consulting/formation_flutter_app/blob/2e95cbd8600012b3178f3218dfe96f9f4db3fd59/lib/src/widgets/counter_info.dart#L9
https://github.com/rushio-consulting/formation_flutter_app/blob/2e95cbd8600012b3178f3218dfe96f9f4db3fd59/lib/src/widgets/increment_button.dart#L8

Provider can trigger rebuild when it's not necessary. 
To avoid that use `Provider.of<Counter>(context, listen: false);`

**Comment by bwnyasse** [comment]
@Kleak  👍
